# Generated by Django 5.2.1 on 2026-04-12 12:12

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_marked_by_student', models.BooleanField(default=False)),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=apps.common.validators.selfie_upload_to)),
                ('selfie_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-registered_at',),
            },
        ),
    ]
