# Generated by Django 5.2.13 on 2026-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
