# Generated by Django 5.2.1 on 2026-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('registration_open', 'Registration open'), ('confirmation_required', 'Confirmation required'), ('finished', 'Finished')], default='registration_open', max_length=30)),
                ('qr_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-start_at',),
            },
        ),
    ]
