# Generated by Django 4.2.30 on 2026-04-21 13:32

import apps.common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=apps.common.validators.mandatory_selfie_upload_to)),
                ('selfie_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_students', to='events.event')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='mandatorystudent',
            constraint=models.UniqueConstraint(fields=('event', 'full_name'), name='uq_event_mandatory_full_name'),
        ),
    ]
